# Generated by Django 4.2.1 on 2023-06-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0002_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='situacao',
            field=models.CharField(choices=[('em andamento', 'Em andamento'), ('encerrado', 'Encerrado')], max_length=100),
        ),
    ]
