# Generated by Django 4.2.1 on 2023-06-05 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0003_alter_projeto_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisadorProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('integrante', 'Integrante'), ('coordenador', 'Coordenador')], max_length=64)),
                ('date_joined', models.DateField()),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPesquisa.pesquisador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPesquisa.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(through='appPesquisa.PesquisadorProjeto', to='appPesquisa.pesquisador'),
        ),
    ]
