# Generated by Django 4.2.1 on 2023-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0004_pesquisadorprojeto_projeto_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('funcionario', 'Funcionário')], max_length=20),
        ),
    ]
