# Generated by Django 4.2.1 on 2023-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appPesquisa", "0005_alter_pesquisador_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto", name="descricao", field=models.TextField(),
        ),
    ]
