# Generated by Django 4.2.1 on 2023-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appPesquisa", "0007_alter_projeto_criado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pesquisadorprojeto",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
    ]
