# Generated by Django 4.2.1 on 2023-07-03 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0008_alter_pesquisadorprojeto_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisadorprojeto',
            name='papel',
            field=models.CharField(choices=[('integrante', 'Integrante'), ('coordenador', 'Coordenador')], default='integrante', max_length=64),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('artigo', 'Artigo'), ('servico', 'Serviço'), ('relatorio', 'Relatório'), ('produto', 'Produto'), ('prototipo', 'Protótipo')], default='artigo', max_length=64)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPesquisa.projeto')),
            ],
        ),
    ]
