# Generated by Django 4.2.1 on 2023-07-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0009_alter_pesquisadorprojeto_papel_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='data',
        ),
    ]
