# Generated by Django 4.2.1 on 2023-07-09 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0010_remove_resultado_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='membros',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='criado_em',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
