# Generated by Django 4.2.1 on 2023-07-08 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0010_remove_resultado_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='area_atuacao',
            field=models.CharField(choices=[('Linguística, Letras e Artes', 'Linguística, Letras e Artes'), ('Ciências Humanas', 'Ciências Humanas'), ('Ciências Sociais Aplicadas', 'Ciências Sociais Aplicadas'), ('Ciências Agrárias', 'Ciências Agrárias'), ('Ciências da Saúde', 'Ciências da Saúde'), ('Engenharias', 'Engenharias'), ('Ciências Biológicas', 'Ciências Biológicas'), ('Ciências Exatas e da Terra', 'Ciências Exatas e da Terra')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='criado_em',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
