# Generated by Django 4.2.1 on 2023-07-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPesquisa', '0011_alter_pesquisador_area_atuacao_and_more'),
        ('appPesquisa', '0011_remove_projeto_membros_alter_projeto_criado_em'),
    ]

    operations = [
    ]
